import type { EmailConnection } from "@prisma/client";
import { v4 as uuid } from "uuid";

import { buildReplySubject, ensureReplyToken, findExistingTicketForMessage } from "./gmail-thread.service";
import { gmailSendService } from "./gmail-send.service";
import type { ParsedEmailMessage } from "./gmail-message.parser";

import { env } from "@/config/env";
import { KAFKA_TOPICS, publishEvent } from "@/lib/kafka";
import { logger } from "@/lib/logger";
import { prisma } from "@/lib/prisma";
import { customersService } from "@/modules/customers/customers.service";
import { automationEngine } from "@/modules/automations/automation-engine.service";
import { computeSlaDueDates, resolveBusinessHours, resolveSlaPolicy } from "@/modules/sla/sla-policy";
import { ticketTrackingService } from "@/modules/ticket-tracking/ticket-tracking.service";
import { emitToOrg, emitToTicket } from "@/sockets";
import { ticketReceivedTemplate } from "@/services/email-templates/ticket-received.template";

export type IngestOutcome =
  | { skipped: true; reason: string }
  | { skipped: false; ticketId: string; created: boolean; inboundMessageId: string };

/**
 * Idempotent by design: re-processing the same gmailMessageId for the same
 * connection is always a no-op (see the unique constraint on
 * InboundEmailMessage), so a retried or re-triggered sync can never create
 * a second ticket, and never appends the same reply twice.
 */
export async function ingestParsedMessage(
  connection: EmailConnection,
  parsed: ParsedEmailMessage,
  forceSkipReason?: string
): Promise<IngestOutcome> {
  const { orgId, id: connectionId, email: connectedInboxEmail } = connection;

  const existing = await prisma.inboundEmailMessage.findUnique({
    where: { connectionId_gmailMessageId: { connectionId, gmailMessageId: parsed.gmailMessageId } },
  });
  if (existing) {
    return { skipped: true, reason: "already_processed" };
  }

  let skipReason: string | null = forceSkipReason ?? null;
  if (!skipReason) {
    if (!parsed.senderEmail) skipReason = "invalid_sender";
    else if (parsed.isSelfSent) skipReason = "self_sent";
    else if (parsed.isDeliveryFailure) skipReason = "delivery_failure";
    else if (parsed.isAutoGenerated) skipReason = "auto_generated_loop";
  }

  // The InboundEmailMessage row is written *before* any ticket side effects
  // — it's the durable record and dedup guard regardless of what happens next.
  const record = await prisma.inboundEmailMessage.create({
    data: {
      orgId,
      connectionId,
      gmailMessageId: parsed.gmailMessageId,
      gmailThreadId: parsed.gmailThreadId,
      internetMessageId: parsed.internetMessageId,
      inReplyTo: parsed.inReplyTo,
      references: parsed.references,
      senderEmail: parsed.senderEmail || "unknown",
      senderName: parsed.senderName,
      recipientEmail: parsed.recipientEmail,
      subject: parsed.subject,
      textBody: parsed.textBody,
      sanitizedHtmlBody: parsed.sanitizedHtmlBody,
      attachments: parsed.attachments as unknown as object,
      receivedAt: parsed.receivedAt,
      processingStatus: skipReason ? "skipped" : "processing",
      processingError: skipReason,
    },
  });

  if (skipReason) {
    return { skipped: true, reason: skipReason };
  }

  try {
    // Feature 8: is this a reply continuing an existing ticket's
    // conversation, rather than a brand new request?
    const existingTicket = await findExistingTicketForMessage(orgId, parsed);
    if (existingTicket) {
      return await appendReplyToTicket(existingTicket.id, record.id, orgId, parsed);
    }

    return await createTicketFromMessage(connection, record.id, parsed);
  } catch (err) {
    const message = err instanceof Error ? err.message : "Unknown ingestion error";
    await prisma.inboundEmailMessage.update({
      where: { id: record.id },
      data: { processingStatus: "failed", processingError: message },
    });
    throw err;
  }
}

async function appendReplyToTicket(
  ticketId: string,
  inboundMessageId: string,
  orgId: string,
  parsed: ParsedEmailMessage
): Promise<IngestOutcome> {
  const { message, ticket } = await prisma.$transaction(async (tx) => {
    const newMessage = await tx.ticketMessage.create({
      data: {
        ticketId,
        authorType: "customer",
        authorId: null,
        body: parsed.textBody?.trim() || "(This email had no readable text content.)",
      },
    });

    const updatedTicket = await tx.ticket.update({
      where: { id: ticketId },
      data: {
        updatedAt: new Date(),
        lastCustomerActivityAt: parsed.receivedAt,
        // Backfills gmailThreadId for tickets that predate this field, or
        // whose first message didn't carry one for some reason.
        ...(parsed.gmailThreadId ? { gmailThreadId: parsed.gmailThreadId } : {}),
      },
    });

    await tx.inboundEmailMessage.update({
      where: { id: inboundMessageId },
      data: { ticketId, processingStatus: "processed" },
    });

    return { message: newMessage, ticket: updatedTicket };
  });

  emitToTicket(ticketId, "ticket:message", message);
  emitToOrg(orgId, "ticket:message", { ticketId, message });
  void publishEvent(KAFKA_TOPICS.CUSTOMER_REPLY_RECEIVED, {
    eventId: uuid(),
    orgId,
    occurredAt: new Date().toISOString(),
    ticketId,
    messageId: message.id,
    gmailMessageId: parsed.gmailMessageId,
  });
  void automationEngine.run(orgId, "customer_replied", ticket, { messageText: parsed.textBody ?? undefined });

  return { skipped: false, ticketId, created: false, inboundMessageId };
}

async function createTicketFromMessage(
  connection: EmailConnection,
  inboundMessageId: string,
  parsed: ParsedEmailMessage
): Promise<IngestOutcome> {
  const { orgId } = connection;

  const org = await prisma.organization.findUnique({ where: { id: orgId } });
  if (!org) throw new Error("Organization not found for this connection");

  const customer = await customersService.findOrCreateByEmail(orgId, parsed.senderEmail, parsed.senderName);

  if (customer.isBlocked) {
    await prisma.inboundEmailMessage.update({
      where: { id: inboundMessageId },
      data: { processingStatus: "skipped", processingError: "customer_blocked" },
    });
    return { skipped: true, reason: "customer_blocked" };
  }

  const subject = parsed.subject?.trim() || "Email support request";
  const initialMessageBody = parsed.textBody?.trim() || "(This email had no readable text content.)";

  const slaPolicy = resolveSlaPolicy(org.slaPolicy);
  const businessHours = resolveBusinessHours(org.businessHours);
  const { firstResponseDueAt, resolutionDueAt } = computeSlaDueDates(
    parsed.receivedAt,
    org.defaultTicketPriority,
    slaPolicy,
    businessHours
  );

  const ticket = await prisma.$transaction(async (tx) => {
    // Same atomic-increment pattern tickets.service.ts uses for
    // dashboard-created tickets — one shared counter, no collisions.
    const updatedOrg = await tx.organization.update({
      where: { id: orgId },
      data: { nextTicketNumber: { increment: 1 } },
      select: { nextTicketNumber: true },
    });
    const number = updatedOrg.nextTicketNumber - 1;

    const newTicket = await tx.ticket.create({
      data: {
        orgId,
        number,
        subject,
        customerId: customer.id,
        channel: "email",
        priority: org.defaultTicketPriority,
        gmailThreadId: parsed.gmailThreadId || null,
        lastCustomerActivityAt: parsed.receivedAt,
        firstResponseDueAt,
        slaBreachAt: resolutionDueAt,
      },
    });

    await tx.ticketMessage.create({
      data: { ticketId: newTicket.id, authorType: "customer", authorId: null, body: initialMessageBody },
    });

    await tx.inboundEmailMessage.update({
      where: { id: inboundMessageId },
      data: { ticketId: newTicket.id, processingStatus: "processed" },
    });

    return newTicket;
  });

  void automationEngine.run(orgId, "ticket_created", ticket, { messageText: initialMessageBody });

  const { rawToken } = await ticketTrackingService.createToken(ticket.id);
  const trackingUrl = `${env.NEXT_PUBLIC_APP_URL}/ticket-track/${rawToken}`;
  const replyToken = await ensureReplyToken(ticket.id);
  const ticketNumber = `SUP-${ticket.number}`;

  const { html, text } = ticketReceivedTemplate({
    customerName: parsed.senderName ?? "there",
    ticketNumber,
    trackingUrl,
    organizationName: org.name,
  });

  // Sent through Gmail itself (not the generic SMTP mail service) — this
  // has to come from the org's own connected inbox, which we only hold
  // OAuth credentials for, not SMTP credentials.
  const ackResult = await gmailSendService.sendReply({
    connection,
    ticketId: ticket.id,
    to: parsed.senderEmail,
    subject: buildReplySubject(ticket.number, subject),
    textBody: text,
    htmlBody: html,
    threadId: ticket.gmailThreadId ?? parsed.gmailThreadId ?? undefined,
    inReplyTo: parsed.internetMessageId ?? undefined,
    replyToken,
    isAutomated: true,
  });

  if (!ackResult.delivered) {
    logger.warn(
      { ticketId: ticket.id, error: ackResult.error },
      "Acknowledgement email was not delivered (ticket was still created)"
    );
    void publishEvent(KAFKA_TOPICS.EMAIL_DELIVERY_FAILED, {
      eventId: uuid(),
      orgId,
      occurredAt: new Date().toISOString(),
      ticketId: ticket.id,
      outboxEventId: "n/a", // this send isn't outbox-driven — see Feature 10 for the outbox path
      reason: ackResult.error ?? "unknown",
    });
  } else if (ackResult.gmailThreadId && ackResult.gmailThreadId !== ticket.gmailThreadId) {
    // First reply on a ticket that had no inbound thread yet — record the
    // thread Gmail assigned so future replies match on it (priority 1).
    await prisma.ticket.update({ where: { id: ticket.id }, data: { gmailThreadId: ackResult.gmailThreadId } });
  }

  emitToOrg(orgId, "ticket:created", ticket);
  void publishEvent(KAFKA_TOPICS.TICKET_CREATED, {
    eventId: uuid(),
    orgId,
    occurredAt: new Date().toISOString(),
    ticketId: ticket.id,
    customerId: customer.id,
    channel: "email",
    subject,
  });

  return { skipped: false, ticketId: ticket.id, created: true, inboundMessageId };
}
