import { convert as htmlToPlainText } from "html-to-text";
import sanitizeHtml from "sanitize-html";

// Deliberately conservative allowlist — email HTML is one of the more
// hostile inputs an app can render. No script/style/iframe/object/embed,
// no event-handler attributes, no non-http(s) links.
const SANITIZE_OPTIONS: sanitizeHtml.IOptions = {
  allowedTags: [
    "a", "b", "strong", "i", "em", "u", "s", "p", "br", "ul", "ol", "li",
    "blockquote", "pre", "code", "span", "div", "table", "thead", "tbody",
    "tr", "td", "th", "h1", "h2", "h3", "h4", "h5", "h6", "hr", "img",
  ],
  allowedAttributes: {
    a: ["href", "title", "target", "rel"],
    img: ["src", "alt", "width", "height"],
    "*": ["style"],
  },
  allowedSchemes: ["http", "https", "mailto"],
  allowedSchemesByTag: { img: ["http", "https", "cid"] },
  // Strip javascript:/data: hrefs and anything else outside the scheme list
  // rather than dropping the whole element — keeps the surrounding content.
  disallowedTagsMode: "discard",
  transformTags: {
    a: sanitizeHtml.simpleTransform("a", { rel: "noopener noreferrer", target: "_blank" }),
  },
};

const MAX_ATTACHMENT_BYTES = 10 * 1024 * 1024; // 10MB per attachment
const BLOCKED_ATTACHMENT_MIME_PATTERNS = [
  /^application\/x-msdownload$/i,
  /^application\/x-executable$/i,
  /^application\/x-sh$/i,
  /^application\/vnd\.microsoft\.portable-executable$/i,
];
const BLOCKED_ATTACHMENT_EXTENSIONS = [".exe", ".bat", ".cmd", ".scr", ".msi", ".com", ".vbs", ".js", ".jar"];

export interface ParsedAttachment {
  filename: string;
  mimeType: string;
  sizeBytes: number;
  gmailAttachmentId: string;
  /** True if size/mime policy blocked it — metadata is kept, content is not fetched. */
  blocked: boolean;
  blockedReason?: string;
}

export interface ParsedEmailMessage {
  gmailMessageId: string;
  gmailThreadId: string;
  internetMessageId: string | null;
  inReplyTo: string | null;
  references: string | null;
  senderEmail: string;
  senderName: string | null;
  recipientEmail: string | null;
  subject: string | null;
  textBody: string | null;
  sanitizedHtmlBody: string | null;
  attachments: ParsedAttachment[];
  receivedAt: Date;
  /** True if the From header's address matches the connected inbox itself. */
  isSelfSent: boolean;
  /** True if headers indicate an autoresponder/mailing-list loop (Auto-Submitted, Precedence: bulk/auto_reply, X-Autoreply). */
  isAutoGenerated: boolean;
  /** True if this looks like a bounce/delivery-failure notice (mailer-daemon, multipart/report, DSN subject patterns). */
  isDeliveryFailure: boolean;
}

// Minimal shape of what we read from googleapis' gmail_v1.Schema$Message —
// declared locally rather than importing the full generated type, since we
// only ever touch this small, stable slice of it.
interface GmailHeader {
  name?: string | null;
  value?: string | null;
}
interface GmailMessagePart {
  mimeType?: string | null;
  filename?: string | null;
  headers?: GmailHeader[] | null;
  body?: { data?: string | null; size?: number | null; attachmentId?: string | null } | null;
  parts?: GmailMessagePart[] | null;
}
export interface RawGmailMessage {
  id?: string | null;
  threadId?: string | null;
  internalDate?: string | null;
  payload?: GmailMessagePart | null;
}

function getHeader(headers: GmailHeader[] | null | undefined, name: string): string | null {
  const match = headers?.find((h) => h.name?.toLowerCase() === name.toLowerCase());
  return match?.value ?? null;
}

function decodeBase64Url(data: string): string {
  return Buffer.from(data, "base64url").toString("utf8");
}

/** Splits `"Jane Doe <jane@example.com>"` into name + email; falls back gracefully for a bare address. */
function parseAddress(raw: string | null): { name: string | null; email: string } {
  if (!raw) return { name: null, email: "" };
  const match = raw.match(/^\s*"?([^"<]*)"?\s*<([^>]+)>\s*$/);
  if (match) {
    const name = match[1].trim();
    return { name: name.length > 0 ? name : null, email: match[2].trim().toLowerCase() };
  }
  return { name: null, email: raw.trim().toLowerCase() };
}

/** Walks the (possibly nested multipart) MIME tree collecting text parts and attachments. */
function walkParts(
  part: GmailMessagePart,
  acc: { text?: string; html?: string; attachments: ParsedAttachment[] }
): void {
  const mimeType = part.mimeType ?? "";
  const hasFilename = Boolean(part.filename && part.filename.length > 0);

  if (hasFilename && part.body?.attachmentId) {
    const sizeBytes = part.body.size ?? 0;
    let blocked = false;
    let blockedReason: string | undefined;

    if (sizeBytes > MAX_ATTACHMENT_BYTES) {
      blocked = true;
      blockedReason = "exceeds size limit";
    } else if (BLOCKED_ATTACHMENT_MIME_PATTERNS.some((re) => re.test(mimeType))) {
      blocked = true;
      blockedReason = "blocked mime type";
    } else if (BLOCKED_ATTACHMENT_EXTENSIONS.some((ext) => part.filename!.toLowerCase().endsWith(ext))) {
      blocked = true;
      blockedReason = "blocked file extension";
    }

    acc.attachments.push({
      filename: part.filename as string,
      mimeType,
      sizeBytes,
      gmailAttachmentId: part.body.attachmentId,
      blocked,
      blockedReason,
    });
    return;
  }

  if (mimeType === "text/plain" && part.body?.data && acc.text === undefined) {
    acc.text = decodeBase64Url(part.body.data);
    return;
  }

  if (mimeType === "text/html" && part.body?.data && acc.html === undefined) {
    acc.html = decodeBase64Url(part.body.data);
    return;
  }

  for (const child of part.parts ?? []) {
    walkParts(child, acc);
  }
}

export function parseGmailMessage(message: RawGmailMessage, connectedInboxEmail: string): ParsedEmailMessage {
  const payload = message.payload ?? {};
  const headers = payload.headers ?? [];

  const from = parseAddress(getHeader(headers, "From"));
  const to = parseAddress(getHeader(headers, "To"));
  const subject = getHeader(headers, "Subject");
  const internetMessageId = getHeader(headers, "Message-ID");
  const inReplyTo = getHeader(headers, "In-Reply-To");
  const references = getHeader(headers, "References");
  const autoSubmitted = getHeader(headers, "Auto-Submitted");
  const precedence = getHeader(headers, "Precedence");
  const contentType = getHeader(headers, "Content-Type");

  const acc: { text?: string; html?: string; attachments: ParsedAttachment[] } = { attachments: [] };
  walkParts(payload, acc);

  const sanitizedHtmlBody = acc.html ? sanitizeHtml(acc.html, SANITIZE_OPTIONS) : null;
  const textBody = acc.text ?? (sanitizedHtmlBody ? htmlToPlainText(sanitizedHtmlBody).trim() : null);

  const isSelfSent = from.email.length > 0 && from.email === connectedInboxEmail.trim().toLowerCase();

  const isAutoGenerated =
    (autoSubmitted !== null && autoSubmitted.toLowerCase() !== "no") ||
    /^(bulk|auto_reply|junk)$/i.test(precedence ?? "") ||
    headers.some((h) => /^x-autoreply$|^x-autorespond$/i.test(h.name ?? ""));

  const isDeliveryFailure =
    from.email.includes("mailer-daemon") ||
    from.email.includes("postmaster") ||
    /^multipart\/report/i.test(contentType ?? "") ||
    /delivery status notification|undelivered mail|mail delivery failed|returned to sender/i.test(
      subject ?? ""
    );

  return {
    gmailMessageId: message.id ?? "",
    gmailThreadId: message.threadId ?? "",
    internetMessageId,
    inReplyTo,
    references,
    senderEmail: from.email,
    senderName: from.name,
    recipientEmail: to.email || null,
    subject,
    textBody,
    sanitizedHtmlBody,
    attachments: acc.attachments,
    receivedAt: message.internalDate ? new Date(Number(message.internalDate)) : new Date(),
    isSelfSent,
    isAutoGenerated,
    isDeliveryFailure,
  };
}
